port: /dev/ttyDXL

joint_order: [waist, shoulder, elbow]
sleep_positions: [0, -1.85, 1.55]

joint_state_publisher:
  update_rate: 100
  publish_states: true
  topic_name: joint_states

groups:
  arm: [waist, shoulder, elbow]

grippers:
#  gripper:
#    horn_radius: 0.022
#    arm_length: 0.036
#    left_finger: left_finger
#    right_finger: right_finger
#
shadows:


sisters:

motors:
  waist:
    ID: 1
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  shoulder:
    ID: 2
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 841
    Max_Position_Limit: 2867
    Secondary_ID: 255


  elbow:
    ID: 3
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 898
    Max_Position_Limit: 3094
    Secondary_ID: 255

