port: /dev/ttyDXL

joint_order: [waist, shoulder, elbow]
sleep_positions: [0.1, 0, 1.55]

joint_state_publisher:
  update_rate: 100
  publish_states: true
  topic_name: joint_states

groups:
  arm: [waist, shoulder, elbow]

grippers:
#  gripper:
#    horn_radius: 0.022
#    arm_length: 0.036
#    left_finger: left_finger
#    right_finger: right_finger
#
shadows:
  shoulder:
    shadow_list: [waist_shadow]
    calibrate: true
  elbow:
    shadow_list: [shoulder_shadow]
    calibrate: true

sisters:

motors:
  waist:
    ID: 1
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 2048
    Max_Position_Limit: 3072
    Secondary_ID: 255

  waist_shadow:
    ID: 2
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 2048   # 0
    Max_Position_Limit: 3072   # 1.57
    Secondary_ID: 1

  shoulder:
    ID: 3
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 1535   # 135, -0.785
    Max_Position_Limit: 2275   # 200, 0.349
    Secondary_ID: 255

  shoulder_shadow:
    ID: 4
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 1535
    Max_Position_Limit: 2275
    Secondary_ID: 3

  elbow:
    ID: 5
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 2275
    Secondary_ID: 255

